#eureka configuration
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

#okta basic configuration
okta:
  oauth2:
    issuer: https://dev-08460809.okta.com/oauth2/default
    audience: api://default
